#pragma once

#define DEFAULT_SCREENWIDTH 1720
#define DEFAULT_SCREENHEIGHT 1080

#define DEFAULT_MAPWIDTH 24
#define DEFAULT_MAPHEIGHT 24

#define DEFAULT_TEXTWIDTH 64
#define DEFAULT_TEXTHEIGHT 64
#define PIXEL_FORMAT SDL_PIXELFORMAT_RGBA8888

